name: Fetch File from Another Repository

on:
  push:
    branches:
      - main

jobs:
  fetch-file:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch file from another repository
      run: |
        curl -H "Authorization: Bearer ${{ secrets.SECRET_SPRINGBOOT }}" -LJO https://github.com/LHZA97/poc-testing-springboot.git/pom.xml
    # mv pom.xml .
    - name: Checkout another repository
      run : ls -al



    
      