name: Fetch File from Another Repository

on:
  push:
    branches:
      - main

jobs:
  fetch-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch file from another repository
      run: |
        git clone https://LHZA97:${{ secrets.SECRET_SPRINGBOOT }}@github.com/LHZA97/poc-testing-springboot.git temp_folder
        ls -al
        cp -R temp_folder/.mvn/* .
        rm -rf temp_folder
    # curl -H "Authorization: Bearer ${{ secrets.SECRET_SPRINGBOOT }}" -LJO https://github.com/LHZA97/poc-testing-springboot.git/pom.xml
    # mv pom.xml .
    - name: Checkout another repository
      run : ls -al



    
      