# name: Run Tests

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   Unit_Tests:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: npm ci

#       - name: Run Jest tests
#         run: npm test -- --coverage

#       - name: Upload Jest coverage report as artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: jest-coverage-report
#           path: coverage/lcov-report
#           if-no-files-found: error

#       - name: Debugging Information
#         run: |
#           ls -l
#           mkdir -p katalon
#           ls -l
#         working-directory: /home/runner

#       - name: Install dependencies
#         run: npm install

#       - name: Install Katalon Studio
#         run: |
#           mkdir -p katalon
#           curl -L https://download.katalon.com/7.9.1/Katalon_Studio_Linux_64-7.9.1.tar.gz | tar xvz -C katalon --strip-components=1

#       - name: Grant execution permissions to Katalon script
#         run: |
#           chmod +x katalon/katalonc.sh
#         working-directory: /home/runner

#       - name: Run Katalon tests
#         run: |
#           cd katalon
#           ./katalonc.sh -noSplash -runMode=console -projectPath=/path/to/your/katalon/project -retry=0 -testSuiteCollectionPath=Test Suites/Collection
#         working-directory: /home/runner

#       - name: Upload Katalon reports
#         uses: actions/upload-artifact@v2
#         with:
#           name: katalon-reports
#           path: katalon/Reports
