name: SonarQube Coverage

on:
  push:
    branches: [sonarqube-coverage]

jobs:
  jest-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install jest-junit
        run: npm install --save-dev jest-junit

      - name: Run Jest tests and generate coverage
        run: npm test

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: jest-tests
    permissions: read-all
    env:
      hostname: ${{ secrets.SONAR_HOST_URL }}
    environment:
      name: sonarqube
      url: ${{ env.hostname }}/dashboard?id=${{env.project_id}}
    steps:
      - name: Set Project ID
        id: set-project-id
        run: |
          repo_full_name="${{ github.repository }}"
          repo_name=$(basename $repo_full_name)
          echo "Repository Name: $repo_name"
          echo "project_id=$repo_name" >> $GITHUB_ENV
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.hostname }}
        with:
          args: >
            -Dsonar.projectKey=LHZA97_poc-testing-nodejs_AYzxoyeny1DwTTyWH5LS
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
      - name: Debug
        run: |
          ls -R
          cat .scannerwork/report-task.txt || echo "File not found"

  sonarqube-quality-gate:
    needs: sonarqube-analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Download SonarQube report
        uses: actions/download-artifact@v3
        with:
          name: sonarqube-report
          path: sonarqube-report
